"""Turn a .nnue file into a C++ byte array so the net ships inside the exe.

    python tools/embed_net.py nets/ix-gen2.nnue build/net_data.cpp

CMake runs this automatically; you never need to call it by hand.
"""

import sys


def main():
    src, dst = sys.argv[1], sys.argv[2]
    data = open(src, "rb").read()
    lines = []
    for i in range(0, len(data), 32):
        lines.append(",".join(str(b) for b in data[i:i + 32]))
    body = ",\n".join(lines)
    with open(dst, "w") as f:
        f.write("// generated by tools/embed_net.py from %s -- do not edit\n" % src.replace("\\", "/"))
        f.write("namespace ix { namespace NNUE {\n")
        f.write("extern const unsigned char EmbeddedNet[] = {\n%s\n};\n" % body)
        f.write("extern const unsigned long EmbeddedNetSize = %d;\n" % len(data))
        f.write("} }\n")


if __name__ == "__main__":
    main()
